import type { Lang } from "@/features/layout/layout-types"

const copy = {
  en: {
    title: "Feature flags",
    subtitle:
      "Control releases and safely manage what users experience in this environment.",
    search: "Filter by name or key",
    tags: "Tags",
    status: "Status",
    any: "Any",
    on: "ON",
    off: "OFF",
    showArchived: "Show archived",
    selected: (count: number) => `${count} selected`,
    copyTo: "Copy to environment",
    clear: "Clear",
    clearAll: "Clear all",
    compare: "Compare",
    newFlag: "New flag",
    name: "Name",
    statusServing: "Status & serving",
    lastChange: "Last change",
    actions: "Actions",
    details: "Details",
    clone: "Clone",
    archive: "Archive",
    restore: "Restore",
    remove: "Remove",
    createdBy: "Created by",
    updatedBy: "Updated by",
    noChanges: "No changes since creation",
    variations: (count: number) => `${count} variations`,
    serving: "Serving",
    copied: "Flag key copied",
    operationSucceeded: "Operation succeeded",
    operationFailed: "Operation failed. Please try again.",
    permissionDenied: "You do not have permission to perform this action.",
    loadFailed: "Feature flags could not be loaded.",
    retry: "Retry",
    empty: "No feature flags yet",
    emptyHelper:
      "Create a flag to control releases without redeploying your application.",
    archivedEmpty: "No archived feature flags",
    archivedEmptyHelper: "Archived flags will appear here.",
    filteredEmpty: "No feature flags match the current filters.",
    clearFilters: "Clear filters",
    showing: (from: number, to: number, total: number) =>
      `Showing ${from} to ${to} of ${total} flags`,
    perPage: (count: number) => `${count} / page`,
    previous: "Previous page",
    next: "Next page",
    moreActions: (name: string) => `More actions for ${name}`,
    copyKey: (key: string) => `Copy flag key ${key}`,
    toggleTitle: (enabled: boolean) =>
      `Turn feature flag ${enabled ? "on" : "off"}?`,
    toggleBody: (enabled: boolean) =>
      enabled
        ? "Targeting and rules will determine the variation served to users."
        : "All users will receive the configured off variation.",
    archiveTitle: "Archive feature flag?",
    archiveBody: (key: string) =>
      `The fallback value in your code will be returned for all users. Remove references to ${key} before archiving.`,
    archiveKeyPromptBefore: "Enter",
    archiveKeyPromptAfter: "to confirm",
    useArchiveKey: (key: string) => `Use feature flag key ${key}`,
    archiveKeyPlaceholder: "Feature flag key",
    restoreTitle: "Restore feature flag?",
    restoreBodyBefore: "Flag",
    restoreBodyAfter: "will return to the active list.",
    removeTitle: "Remove feature flag permanently?",
    removeBodyBefore: "Flag",
    removeBodyAfter:
      "will be permanently removed. This operation cannot be undone.",
    cancel: "Cancel",
    confirm: "Confirm",
    allTags: "All tags",
    noTags: "No tags found",
    tagPlaceholder: "Search or create tag",
    tagsLoadFailed: "Tags could not be loaded.",
    availableTags: "Available tags",
    loading: "Loading…",
    createTag: (tag: string) => `Create “${tag}”`,
    removeTag: (tag: string) => `Remove tag ${tag}`,
  },
  zh: {
    title: "功能开关",
    subtitle: "控制发布，并安全地管理当前环境中用户的体验。",
    search: "按名称或键筛选",
    tags: "标签",
    status: "状态",
    any: "任意",
    on: "开启",
    off: "关闭",
    showArchived: "显示已归档",
    selected: (count: number) => `已选择 ${count} 项`,
    copyTo: "复制到环境",
    clear: "清除",
    clearAll: "清除全部",
    compare: "比较",
    newFlag: "新建功能开关",
    name: "名称",
    statusServing: "状态与返回值",
    lastChange: "最近变更",
    actions: "操作",
    details: "详情",
    clone: "克隆",
    archive: "归档",
    restore: "恢复",
    remove: "移除",
    createdBy: "创建者",
    updatedBy: "更新者",
    noChanges: "创建后暂无变更",
    variations: (count: number) => `${count} 个变体`,
    serving: "返回值",
    copied: "已复制功能开关键",
    operationSucceeded: "操作成功",
    operationFailed: "操作失败，请重试。",
    permissionDenied: "你没有执行此操作的权限。",
    loadFailed: "无法加载功能开关。",
    retry: "重试",
    empty: "暂无功能开关",
    emptyHelper: "创建功能开关，无需重新部署即可控制发布。",
    archivedEmpty: "暂无已归档的功能开关",
    archivedEmptyHelper: "已归档的功能开关会显示在这里。",
    filteredEmpty: "没有功能开关匹配当前筛选条件。",
    clearFilters: "清除筛选",
    showing: (from: number, to: number, total: number) =>
      `显示第 ${from} 至 ${to} 项，共 ${total} 个功能开关`,
    perPage: (count: number) => `每页 ${count} 项`,
    previous: "上一页",
    next: "下一页",
    moreActions: (name: string) => `${name} 的更多操作`,
    copyKey: (key: string) => `复制功能开关键 ${key}`,
    toggleTitle: (enabled: boolean) => `${enabled ? "开启" : "关闭"}功能开关？`,
    toggleBody: (enabled: boolean) =>
      enabled
        ? "将根据用户定向和规则返回变体。"
        : "所有用户将收到配置的关闭变体。",
    archiveTitle: "归档功能开关？",
    archiveBody: (key: string) =>
      `所有用户将收到代码中的回退值。归档前请移除对 ${key} 的引用。`,
    archiveKeyPromptBefore: "请输入",
    archiveKeyPromptAfter: "以确认",
    useArchiveKey: (key: string) => `使用功能开关键 ${key}`,
    archiveKeyPlaceholder: "功能开关键",
    restoreTitle: "恢复功能开关？",
    restoreBodyBefore: "功能开关",
    restoreBodyAfter: "将返回活动列表。",
    removeTitle: "永久删除功能开关？",
    removeBodyBefore: "功能开关",
    removeBodyAfter: "将被永久移除。此操作无法撤销。",
    cancel: "取消",
    confirm: "确认",
    allTags: "全部标签",
    noTags: "未找到标签",
    tagPlaceholder: "搜索或创建标签",
    tagsLoadFailed: "无法加载标签。",
    availableTags: "可用标签",
    loading: "加载中…",
    createTag: (tag: string) => `创建“${tag}”`,
    removeTag: (tag: string) => `移除标签 ${tag}`,
  },
}

export function flagsCopy(lang: Lang) {
  return copy[lang]
}
