apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  containers:
    - env:
        - name: MONGO_INITDB_DATABASE
          value: featbit
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
      image: mongo:5.0.14
      name: mongodb
      ports:
        - containerPort: 27017
      resources: {}
      volumeMounts:
        - mountPath: /data/db
          name: mongodb
        - mountPath: /docker-entrypoint-initdb.d
          name: mongodb-init
  restartPolicy: OnFailure
  volumes:
    - name: mongodb
      persistentVolumeClaim:
        claimName: mongodb
    - name: mongodb-init
      configMap:
        name: mongodb-init
        items:
          - key: "init.js"
            path: "init.js"
        

status: {}
