server {
  listen 3000;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /release-decision {
    return 308 /release-decision/;
  }

  location /release-decision/ {
    try_files $uri $uri/ /release-decision/index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
