apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: clickhouse-server
  name: clickhouse-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
