apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
data:
  agent.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
      filelog:
        include: ["/var/log/clickhouse-server/*.log"]
        start_at: beginning
        include_file_path: true
        include_file_name: false
        operators:
          - type: file_input
            include: 
              - /var/log/clickhouse-server/clickhouse-server.err.log
          - type: regex_parser
            regex: '^(?P<timestamp>[^\s]+ [^\s]+) \[\s(?P<error_num>\d)\s\] {} \<(?P<logtag>[A-Za-z]+)\> (?P<stream>[A-Za-z]+): (?P<message>.*)'
          - type: recombine
            combine_field: body.message
            combine_with: ""
            is_last_entry: "body.logtag == 'F'"
            overwrite_with: "newest"
          # - type: recombine
          #   combine_field: body.message
          #   is_first_entry: body.message matches "^[^\s]"
    processors:
    exporters:
      otlp:
        endpoint: "signoz-test-otel-collector.signoz.svc.cluster.local:4317"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp]
        logs:
          receivers: [filelog]
          processors: []
          exporters: [otlp]