apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-aggregate
  name: kafka-aggregate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
