apiVersion: v1
kind: Pod
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  initContainers:
        
        - name: volume-permissions
          image: bitnami/zookeeper:3.8.1
          command:
            - /bin/bash
          args:
            - -ec
            - |
              mkdir -p /bitnami/zookeeper
              chown -R 1001:1001 /bitnami/zookeeper
              find /bitnami/zookeeper -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs -r chown -R 1001:1001

          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
          resources: 
            requests:
              memory: 1Gi
              cpu: 500m
              ephemeral-storage: 256Mi 
            limits:
              memory: 2Gi
              cpu: 500m
              ephemeral-storage: 512Mi 
          volumeMounts:
            - name: zookeeper
              mountPath: /bitnami/zookeeper
  containers:
    - env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "true"
      image: bitnami/zookeeper:3.8.1
      name: zookeeper
      ports:
        - containerPort: 2181
      resources: 
        requests:
          memory: 1Gi
          cpu: 500m
          ephemeral-storage: 2Gi 
        limits:
          memory: 2Gi
          cpu: 500m
          ephemeral-storage: 4Gi 
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      volumeMounts:
        - mountPath: /bitnami/zookeeper
          name: zookeeper
        - name: zoo-cfg
          mountPath: /opt/bitnami/zookeeper/conf/zoo.cfg
          subPath: "zoo.cfg"
          readOnly: true
  restartPolicy: OnFailure
  volumes:
    - name: zookeeper
      persistentVolumeClaim:
        claimName: zookeeper
    - name: zoo-cfg
      configMap:
        name: zookeeper-config
status: {}
