apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-server
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  strategy: {}
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - env:
            - name: MongoDb__ConnectionString
              value: mongodb://admin:password@mongodb:27017
            - name: MongoDb__Database
              value: featbit
            - name: OLAP__ServiceHost
              value: http://da-server:8200
            - name: Redis__ConnectionString
              value: redis:6379
          image: featbit/featbit-api-server:latest
          name: api-server
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
      restartPolicy: Always
status: {}
