apiVersion: v1
kind: Service
metadata:
  labels:
    app: da-server
  name: da-server
spec:
  ports:
    - name: "8200"
      port: 8200
      targetPort: 80
  selector:
    app: da-server
status:
  loadBalancer: {}
