import type {
  HealthMonitor,
  HealthSession,
  MetricPoint,
  ReleaseMetric,
} from "./release-health-types"

function points(values: number[], startHour = 9): MetricPoint[] {
  return values.map((value, index) => {
    const minute = index * 5
    const hour = startHour + Math.floor(minute / 60)
    const minutes = String(minute % 60).padStart(2, "0")
    return {
      time: `2026-08-28T${String(hour).padStart(2, "0")}:${minutes}:00+08:00`,
      label: `${String(hour).padStart(2, "0")}:${minutes}`,
      value,
    }
  })
}

export const releaseMetrics: ReleaseMetric[] = [
  {
    id: "metric-error-rate",
    key: "checkout_error_rate",
    name: "Checkout error rate",
    description: "Failed checkout requests divided by all checkout requests.",
    category: "quality",
    valueType: "ratio",
    calculation: "numerator-over-denominator",
    unit: "percent",
    version: 3,
    usedByMonitors: 3,
    usedByFlags: ["checkout-redesign", "payment-routing"],
    environment: {
      dataStatus: "ready",
      value: 2.7,
      displayValue: "2.7%",
      changeLabel: "+1.1 pp in 30 min",
      updatedAt: "35 sec ago",
      coverage: 99.4,
      sourceBinding: {
        sourceType: "featbit-events",
        sourceLabel: "FeatBit telemetry",
        selector: "request_error / checkout_request",
        bindingRevision: 4,
        contextCapabilities: ["flag-key", "variation", "exposure"],
      },
      history: points([
        0.9, 1.1, 1, 1.2, 1.1, 1.3, 1.4, 1.5, 1.6, 1.8, 2.1, 2.4, 2.6, 2.8, 2.7,
        2.9, 2.7,
      ]),
    },
  },
  {
    id: "metric-api-latency",
    key: "api_p95_latency",
    name: "API P95 latency",
    description: "95th percentile latency across the checkout API service.",
    category: "reliability",
    valueType: "distribution",
    calculation: "p95",
    unit: "milliseconds",
    version: 5,
    usedByMonitors: 6,
    usedByFlags: ["checkout-redesign", "payment-routing", "recommendations-v2"],
    environment: {
      dataStatus: "ready",
      value: 842,
      displayValue: "842 ms",
      changeLabel: "+18% in 30 min",
      updatedAt: "42 sec ago",
      coverage: 98.8,
      sourceBinding: {
        sourceType: "prometheus",
        sourceLabel: "Prometheus-compatible",
        selector:
          "histogram_quantile(0.95, sum(rate(http_server_duration_bucket[5m])) by (le))",
        connectionName: "Production metrics",
        bindingRevision: 6,
        contextCapabilities: [],
      },
      history: points([
        610, 625, 604, 632, 650, 671, 688, 721, 760, 790, 815, 832, 847, 861,
        852, 848, 842,
      ]),
    },
  },
  {
    id: "metric-completion",
    key: "checkout_completion_rate",
    name: "Checkout completion",
    description: "Sessions that complete checkout after entering the flow.",
    category: "impact",
    valueType: "ratio",
    calculation: "numerator-over-denominator",
    unit: "percent",
    version: 2,
    usedByMonitors: 2,
    usedByFlags: ["checkout-redesign"],
    environment: {
      dataStatus: "ready",
      value: 68.4,
      displayValue: "68.4%",
      changeLabel: "-0.8 pp in 30 min",
      updatedAt: "1 min ago",
      coverage: 96.7,
      sourceBinding: {
        sourceType: "featbit-events",
        sourceLabel: "FeatBit telemetry",
        selector: "checkout_completed / exposed_users",
        bindingRevision: 3,
        contextCapabilities: ["flag-key", "variation", "exposure"],
      },
      history: points([
        70.1, 70.4, 70.2, 69.9, 70, 69.8, 69.5, 69.3, 69.1, 68.9, 69, 68.8,
        68.6, 68.5, 68.7, 68.5, 68.4,
      ]),
    },
  },
  {
    id: "metric-memory",
    key: "service_memory_saturation",
    name: "Service memory saturation",
    description:
      "Memory working-set saturation for services in this environment.",
    category: "reliability",
    valueType: "gauge",
    calculation: "maximum",
    unit: "percent",
    version: 1,
    usedByMonitors: 4,
    usedByFlags: ["checkout-redesign", "search-ranking-v3"],
    environment: {
      dataStatus: "stale",
      value: 76,
      displayValue: "76%",
      changeLabel: "last complete window",
      updatedAt: "12 min ago",
      coverage: 61.2,
      sourceBinding: {
        sourceType: "prometheus",
        sourceLabel: "Prometheus-compatible",
        selector:
          "max(process_memory_working_set_bytes / container_memory_limit_bytes)",
        connectionName: "Production metrics",
        bindingRevision: 2,
        contextCapabilities: [],
      },
      history: points([
        62, 63, 61, 64, 66, 68, 70, 72, 73, 74, 75, 76, 76, 76, 76, 76, 76,
      ]),
    },
  },
  {
    id: "metric-crash-free",
    key: "crash_free_sessions",
    name: "Crash-free sessions",
    description: "Percentage of application sessions without a crash signal.",
    category: "quality",
    valueType: "ratio",
    calculation: "one-minus-ratio",
    unit: "percent",
    version: 1,
    usedByMonitors: 1,
    usedByFlags: ["mobile-navigation"],
    environment: {
      dataStatus: "collecting",
      value: null,
      displayValue: "—",
      changeLabel: "warm-up in progress",
      updatedAt: "receiving events",
      coverage: 38.5,
      sourceBinding: {
        sourceType: "featbit-events",
        sourceLabel: "FeatBit telemetry",
        selector: "1 - app_crash / app_session",
        bindingRevision: 1,
        contextCapabilities: ["flag-key", "variation", "exposure"],
      },
      history: points([99.8, 99.7, 99.8, 99.7, 99.6, 99.7]),
    },
  },
]

export const checkoutMonitor: HealthMonitor = {
  id: "monitor-checkout-safety",
  name: "Checkout safety monitor",
  flagKey: "checkout-redesign",
  enabled: true,
  mode: "continuous",
  triggers: ["manual", "flag-change", "schedule", "api"],
  bindings: [
    {
      metricId: "metric-error-rate",
      observationMode: "flag-contextual",
      purpose: "guard",
      rule: "> 2% for 5 min",
      noDataPolicy: "notify",
      healthStatus: "critical",
      gateBlocking: true,
    },
    {
      metricId: "metric-api-latency",
      observationMode: "environment",
      purpose: "guard",
      rule: "> 800 ms for 10 min",
      noDataPolicy: "wait",
      healthStatus: "critical",
      gateBlocking: true,
    },
    {
      metricId: "metric-completion",
      observationMode: "flag-contextual",
      purpose: "observe",
      rule: "Observe trend",
      noDataPolicy: "wait",
      healthStatus: "healthy",
      gateBlocking: false,
    },
    {
      metricId: "metric-memory",
      observationMode: "environment",
      purpose: "guard",
      rule: "> 85% for 10 min",
      noDataPolicy: "notify",
      healthStatus: "not-evaluated",
      gateBlocking: true,
    },
  ],
  warmup: "5 min",
  lookback: "10 min",
  evaluationInterval: "1 min",
  sustain: "5 min",
  actions: ["Alert owners", "Rich webhook", "Require approval"],
  updatedAt: "2026-08-27T15:24:00+08:00",
}

export const healthSessions: HealthSession[] = [
  {
    id: "session-checkout-042",
    displayId: "HS-042",
    monitorId: checkoutMonitor.id,
    monitorName: checkoutMonitor.name,
    flagKey: "checkout-redesign",
    flagName: "Checkout redesign",
    trigger: "flag-change",
    triggerLabel: "UI flag change",
    status: "active",
    gateStatus: "approval-required",
    dataStatus: "ready",
    startedAt: "2026-08-28T10:12:00+08:00",
    revisionBefore: "rev_9d1c21",
    revisionAfter: "rev_a84f03",
    changeSummary: "Rollout changed from 10% to 25%",
    assessments: [
      {
        metricId: "metric-error-rate",
        observationMode: "flag-contextual",
        purpose: "guard",
        dataStatus: "ready",
        healthStatus: "critical",
        observedValue: "2.7%",
        rule: "> 2% for 5 min",
        reason: "Threshold exceeded for 7 consecutive minutes.",
        evidenceWindow: "10:28–10:38",
        gateBlocking: true,
      },
      {
        metricId: "metric-api-latency",
        observationMode: "environment",
        purpose: "guard",
        dataStatus: "ready",
        healthStatus: "critical",
        observedValue: "842 ms",
        rule: "> 800 ms for 10 min",
        reason: "Environment-wide latency remained above the configured rule.",
        evidenceWindow: "10:24–10:38",
        gateBlocking: true,
      },
      {
        metricId: "metric-completion",
        observationMode: "flag-contextual",
        purpose: "observe",
        dataStatus: "ready",
        healthStatus: "healthy",
        observedValue: "68.4%",
        rule: "Observe trend",
        reason:
          "A small decrease was observed; this metric does not control the gate.",
        evidenceWindow: "10:12–10:38",
        gateBlocking: false,
      },
      {
        metricId: "metric-memory",
        observationMode: "environment",
        purpose: "guard",
        dataStatus: "stale",
        healthStatus: "not-evaluated",
        observedValue: "76%",
        rule: "> 85% for 10 min",
        reason: "Latest complete sample is older than the allowed data delay.",
        evidenceWindow: "last complete window",
        gateBlocking: true,
      },
    ],
    events: [
      {
        id: "event-1",
        occurredAt: "10:12",
        kind: "session",
        title: "Observation started",
        description:
          "Snapshot created for revision rev_a84f03 after the UI change.",
        result: "success",
      },
      {
        id: "event-2",
        occurredAt: "10:17",
        kind: "assessment",
        title: "Warm-up completed",
        description:
          "All ready metrics entered the first 10-minute lookback window.",
        result: "success",
      },
      {
        id: "event-3",
        occurredAt: "10:33",
        kind: "assessment",
        title: "Guard entered Critical",
        description: "Checkout error rate exceeded its rule for five minutes.",
        result: "warning",
      },
      {
        id: "event-4",
        occurredAt: "10:34",
        kind: "alert",
        title: "Alert and Rich Webhook delivered",
        description:
          "Release owners were notified with a link to this evidence.",
        result: "success",
      },
      {
        id: "event-5",
        occurredAt: "10:35",
        kind: "action",
        title: "Approval required",
        description:
          "Further release action is waiting for an authorized reviewer.",
        result: "pending",
      },
    ],
    snapshot: {
      createdAt: "2026-08-28T10:12:03+08:00",
      metricVersions: [
        "checkout_error_rate v3",
        "api_p95_latency v5",
        "checkout_completion_rate v2",
        "service_memory_saturation v1",
      ],
      warmup: "5 min",
      lookback: "10 min",
      evaluationInterval: "1 min",
      sustain: "5 min",
      noDataPolicy: "Wait for required data; notify on Stale or Error",
      actions: ["Alert owners", "Rich webhook", "Require approval"],
    },
  },
  {
    id: "session-checkout-041",
    displayId: "HS-041",
    monitorId: checkoutMonitor.id,
    monitorName: checkoutMonitor.name,
    flagKey: "checkout-redesign",
    flagName: "Checkout redesign",
    trigger: "manual",
    triggerLabel: "Quick observation",
    status: "completed",
    gateStatus: "passing",
    dataStatus: "ready",
    startedAt: "2026-08-27T16:20:00+08:00",
    endedAt: "2026-08-27T17:20:00+08:00",
    revisionBefore: "rev_9d1c21",
    revisionAfter: "rev_9d1c21",
    changeSummary: "Observed current revision without changing the flag",
    assessments: [],
    events: [],
    snapshot: {
      createdAt: "2026-08-27T16:20:00+08:00",
      metricVersions: ["checkout_error_rate v3", "api_p95_latency v5"],
      warmup: "5 min",
      lookback: "10 min",
      evaluationInterval: "1 min",
      sustain: "5 min",
      noDataPolicy: "Wait",
      actions: ["Alert owners"],
    },
  },
  {
    id: "session-pricing-019",
    displayId: "HS-019",
    monitorId: "monitor-pricing",
    monitorName: "Pricing page watch",
    flagKey: "pricing-layout-v2",
    flagName: "Pricing layout v2",
    trigger: "schedule",
    triggerLabel: "Scheduled change",
    status: "active",
    gateStatus: "waiting",
    dataStatus: "collecting",
    startedAt: "2026-08-28T10:31:00+08:00",
    revisionBefore: "rev_813a12",
    revisionAfter: "rev_b95d20",
    changeSummary: "Scheduled rollout changed from 0% to 10%",
    sourceReference: "Schedule association available",
    assessments: [],
    events: [],
    snapshot: {
      createdAt: "2026-08-28T10:31:02+08:00",
      metricVersions: ["pricing_conversion v4"],
      warmup: "10 min",
      lookback: "15 min",
      evaluationInterval: "2 min",
      sustain: "5 min",
      noDataPolicy: "Wait",
      actions: ["Alert owners"],
    },
  },
  {
    id: "session-search-008",
    displayId: "HS-008",
    monitorId: "monitor-search",
    monitorName: "Search reliability",
    flagKey: "search-ranking-v3",
    flagName: "Search ranking v3",
    trigger: "api",
    triggerLabel: "API flag change",
    status: "stopped",
    gateStatus: "breached",
    dataStatus: "error",
    startedAt: "2026-08-26T14:05:00+08:00",
    endedAt: "2026-08-26T15:11:00+08:00",
    revisionBefore: "rev_22a0d4",
    revisionAfter: "rev_31d7cb",
    changeSummary: "Targeting rule updated through API",
    assessments: [],
    events: [],
    snapshot: {
      createdAt: "2026-08-26T14:05:02+08:00",
      metricVersions: ["search_error_rate v2", "api_p95_latency v5"],
      warmup: "5 min",
      lookback: "10 min",
      evaluationInterval: "1 min",
      sustain: "5 min",
      noDataPolicy: "Notify and block",
      actions: ["Alert owners", "Rich webhook"],
    },
  },
]

export function metricById(metricId: string) {
  return releaseMetrics.find((metric) => metric.id === metricId)
}

export function metricByKey(metricKey: string) {
  return releaseMetrics.find((metric) => metric.key === metricKey)
}

export function sessionById(sessionId: string) {
  return healthSessions.find((session) => session.id === sessionId)
}
