name: featbit-dev-postgres-clickhouse
services:
  ui:
    image: featbit/ui:dev
    container_name: ui
    build:
      context: ./modules/front-end
      dockerfile: ./Dockerfile
    environment:
      - API_URL=http://localhost:5000
      - DEMO_URL=http://localhost:5173
      - EVALUATION_URL=http://localhost:5100
    depends_on:
      - api-server
      - demo-dino-game-vue
    ports:
      - "8081:80"
    networks:
      - featbit-network

  api-server:
    image: featbit/api:dev
    container_name: api
    build:
      context: ./modules/back-end
      dockerfile: ./deploy/Dockerfile
    environment:
      - SSOEnabled=true
      - DbProvider=Postgres
      - MqProvider=Kafka
      - Postgres__ConnectionString=Host=postgresql;Port=5432;Username=postgres;Password=0tJXCokSvOB8;Database=featbit
      - Kafka__Producer__bootstrap.servers=kafka:9092
      - Kafka__Consumer__bootstrap.servers=kafka:9092
      - Redis__ConnectionString=redis:6379
      - OLAP__ServiceHost=http://da-server
    depends_on:
      - postgresql
      - redis
      - da-server
    ports:
      - "5000:5000"
    networks:
      - featbit-network

  evaluation-server:
    image: featbit/evaluation-server:dev
    container_name: evaluation-server
    build:
      context: ./modules/evaluation-server
      dockerfile: ./deploy/Dockerfile
    environment:
      - DbProvider=Postgres
      - MqProvider=Kafka
      - Postgres__ConnectionString=Host=postgresql;Port=5432;Username=postgres;Password=0tJXCokSvOB8;Database=featbit
      - Kafka__Producer__bootstrap.servers=kafka:9092
      - Kafka__Consumer__bootstrap.servers=kafka:9092
      - Redis__ConnectionString=redis:6379
    depends_on:
      - postgresql
      - kafka
      - redis
    ports:
      - "5100:5100"
    networks:
      - featbit-network

  da-server:
    image: featbit/data-analytics-server:dev
    container_name: data-analytics-server
    build:
      context: ./modules/data-analytics
      dockerfile: ./Dockerfile
    depends_on:
      - kafka
      - clickhouse-server
    ports:
      - "8200:80"
    networks:
      - featbit-network
    environment:
      DB_PROVIDER: ClickHouse
      KAFKA_HOSTS: kafka:9092
      CLICKHOUSE_HOST: clickhouse-server
      CLICKHOUSE_KAFKA_HOSTS: kafka:9092
      CHECK_DB_LIVNESS: true

  kafka:
    image: bitnami/kafka:3.5
    restart: on-failure
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'true'
    networks:
      - featbit-network
    volumes:
      - kafka:/bitnami/kafka
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=featbit-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - featbit-network
  
  init-kafka-topics:
    image: bitnami/kafka:3.5
    depends_on:
      kafka:
        condition: service_started
    networks:
      - featbit-network
    entrypoint:
      - bash
      - "-c"
      - |
        echo "Waiting for Kafka to be ready..."
        until /opt/bitnami/kafka/bin/kafka-topics.sh --list --bootstrap-server kafka:9092; do sleep 5; done;
        echo "Kafka is ready now, start creating topics."
        /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic featbit-feature-flag-change;
        /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic featbit-segment-change;
        /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic featbit-endusers;
        /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic featbit-insights;
        echo "Seed kafka topic finished."

  clickhouse-server:
    image: clickhouse/clickhouse-server:23.7
    container_name: clickhouse-server
    restart: on-failure
    depends_on:
      - kafka
    ports:
      - "8123:8123"
      - "8443:8443"
      - "9000:9000"
      - "9009:9009"
      - "9440:9440"
      - "9181:9181"
    networks:
      - featbit-network
    volumes:
      - ./infra/clickhouse/single_node/config.xml:/etc/clickhouse-server/config.xml
      - ./infra/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - clickhouse-server:/var/lib/clickhouse

  postgresql:
    image: postgres:15.10
    container_name: postgresql
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0tJXCokSvOB8
    volumes:
      - ./infra/postgresql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    networks:
      - featbit-network

  redis:
    image: bitnami/redis:6.2.10
    container_name: redis
    restart: on-failure
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - featbit-network
    ports:
      - "6379:6379"
    volumes:
      - redis:/bitnami/redis/data

  demo-dino-game-vue:
    image: featbit/demo-dino-game-vue:latest
    container_name: demo-dino-game-vue
    networks:
      - featbit-network
    ports:
      - "5173:80"

networks:
  featbit-network:
    name: featbit-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.0.0/16

volumes:
  redis:
  kafka:
  postgres_data:
  clickhouse-server:

