name: featbit-otel-collector
version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./infra/otel/otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
      - ./.logs/otel:/otel:rw
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      - featbit-network
    depends_on:
      jaeger:
        condition: service_started
      prometheus:
        condition: service_started
      seq:
        condition: service_started
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - featbit-network
    ports:
      - "16686:16686" # Jaeger Web UI
      # - "14317" # trace port
      # - "14268"
      - "14250"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./infra/otel/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    networks:
      - featbit-network
    ports:
      - "9090:9090"
  seq:
    image: datalust/seq:latest
    container_name: seq
    networks:
      - featbit-network
    ports:
      - 8082:80
      - 5341:5341
    volumes:
      - seq:/data
    environment:
      - ACCEPT_EULA=Y 
networks:
  featbit-network:
    name: featbit-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16

volumes:
  prometheus:
  seq: