apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-dino-game-vue
  name: demo-dino-game-vue
spec:
  ports:
    - name: "5173"
      port: 5173
      targetPort: 80
  selector:
    app: demo-dino-game-vue
  type: ClusterIP
status:
  loadBalancer: {}