# Validate the api-server and evaluation-server when code changes

name: API-Server change validations
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'modules/back-end/**'
      - '.github/api-server-validations.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'modules/back-end/**'
      - '.github/api-server-validations.yml'

jobs:
  validate:
    name: Validate API-Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build - API-Server
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:modules/back-end"
          file: ./deploy/Dockerfile
          platforms: linux/amd64
          push: false
