name: Build and Test API-Server
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'modules/back-end/**'
      - '.github/build-and-test-api.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'modules/back-end/**'
      - '.github/build-and-test-api.yml'

jobs:
  validate:
    name: build-and-test-els
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Packages
        run: dotnet restore
        working-directory: modules/back-end

      - name: Build Solution
        run: dotnet build -c Release --no-restore
        working-directory: modules/back-end

      - name: Run Tests
        run: dotnet test -c Release --no-build --verbosity normal --logger GitHubActions
        working-directory: modules/back-end
