name: Publish Docker Images

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Dockerhub image version (For example: 1.0.0)"
        required: true
      build-latest:
        description: "Build and publish latest image"
        type: boolean
        default: false
        required: false

env:
  LATEST_TAG: latest
  VERSION_TAG: ${{ github.event.inputs.version }}

jobs:
  build-publish:
    name: Build and publish image to Docker Hub
    runs-on: ubuntu-latest
    environment: Production
    strategy:
      matrix:
        app: [featbit-ui, featbit-api-server, featbit-data-analytics-server, featbit-evaluation-server]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"

      - name: Set Dockerfile Subdirectory
        id: set-dockerfile-subdirectory
        run: |
          declare -A app_subdir_map
          app_subdir_map=(
            ["featbit-api-server"]="modules/back-end/deploy"
            ["featbit-data-analytics-server"]="modules/data-analytics"
            ["featbit-evaluation-server"]="modules/evaluation-server/deploy"
            ["featbit-ui"]="modules/frontend"
          )
          echo "subdirectory=${app_subdir_map[${{ matrix.app }}]}"

      - name: Build and push - ${{ matrix.app }} (${{ env.VERSION_TAG }})
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ steps.set-dockerfile-subdirectory.outputs.subdirectory }}"
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.app }}:${{ env.VERSION_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push - ${{ matrix.app }} (${{ env.LATEST_TAG }})
        if: github.event.inputs.build-latest
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:${{ steps.set-dockerfile-subdirectory.outputs.subdirectory }}"
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.app }}:${{ env.LATEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
